fix: Fail early for storage size mismatch in EC2 Throw an exception during build time if the EC2 runner storage size is smaller than the AMI size set in the image builder. This could result in errors like:
```
Ec2.Ec2Exception: Volume of size 30GB is smaller than snapshot 'snap-0123456789abc', expect size>= 100GB
```