fix: Missing dependency on AMI builder (#368)
This caused errors like:
```
Error: The stack named Any failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: lt-XXXXXXXXXXXXXXX doesn't have an AMI (RequestId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)
```
The custom resource tried to read the AMI disk type from the launch template before the AMI was created. Wait until the AMI is created before running the custom resource.

Fixes #367