fix: Metric methods shouldn't accept or require namespace and name parameters (#846)
This caused errors like the following in Python:

```
TypeError: GitHubRunners.metric_failed() missing 2 required keyword-only arguments: 'metric_name' and 'namespace'
```

It also required users to pass namespace and metric name (that were ignored) if they wanted to customize the metric.