fix: Action S3Download has no inputs; it requires an 'inputs' (#965)
AMI image builder started failing due to a recent AWS change. They hardened the schema for EC2 Image Builder a bit and we can no longer pass `S3Download` step with empty inputs.

```
Parsing step 'Download' in phase 'build' failed.
Error: Action S3Download has no inputs; it requires an 'inputs'
```

The fix is to adhere to this new schema and not include empty `S3Download` steps.

Fixes #964.